# ????
channelName = fsims-channel

# ??????
privateKeyPath = ./FabricUpload/src/main/java/config/fabric_organizations/peerOrganizations/org1/users/User1@org1/msp/keystore/sk

# ??????
certificatePath = ./FabricUpload/src/main/java/config/fabric_organizations/peerOrganizations/org1/users/User1@org1/msp/signcerts/cert.pem

# ????????
networkConfigPath = ./FabricUpload/src/main/java/config/fabric__connection.json

walletPath = ./FabricUpload/src/main/java/fabric_wallet

networkConfigPathYaml = ./FabricUpload/src/main/java/config/fabric_connection.yaml